### ISSUE TITLE
Upsunified Laravel has wrong DATABASE_URL

### ISSUE THREAD

**Issue by tejapsh** [platformsh/platformify#174]
After `php artisan migrate --force` we get
```
   In Connection.php line 760:
      SQLSTATE[HY000] [2002] Connection timed out
```
echo $DATABASE_URL
```
mysql://user:@xyz:3306/main
```

The value in `.environment`,
```
DATABASE_URL="${DB_SCHEME}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:${DB_PORT}/${DB_PATH}"
``` 

Changing `.environment` to:
```
export DATABASE_URL="${MARIADB_SCHEME}://${MARIADB_USERNAME}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_PATH}"
```
Works.

**Comment by tejapsh** [comment]
https://github.com/platformsh/platformify/blob/836f8b688a8ab6a0a604cc65c71c18b10db13c15/platformifier/models.go#L93 should return `service.Type`.

**Comment by OriPekelman** [comment]
1. The whole .environment stuff is no longer necessary - we are expanding the variables in the images themselves - we just need to construct the final DATABASE_URL
2. The issue with the current implementation is that we are using the wrong property. This is wrong: https://github.com/platformsh/platformify/blob/836f8b688a8ab6a0a604cc65c71c18b10db13c15/platformifier/templates/upsun/.environment#L11 this is correct: https://github.com/platformsh/platformify/blob/836f8b688a8ab6a0a604cc65c71c18b10db13c15/platformifier/templates/generic/.environment#L11 @tejapsh I don't know if there is an issue with the model you cited but it is an unrelated issue.
