### ISSUE TITLE
Strapi: `project:init` return the wrong .environment file 

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformify#178]
Hi @akalipetis 

I start writing the Upsun Strapi guide and i needed to change all of the envVars in it as it is not well design for Strapi.
This is what i get: 
```
export RELATIONSHIPS_JSON="$(echo $PLATFORM_RELATIONSHIPS | base64 --decode)"

# Set database environment variables
export DB_HOSTNAME="$POSTGRESQL_HOSTNAME"
export DB_PORT="$POSTGRESQL_PORT"
export DB_PATH="$POSTGRESQL_PATH"
export DB_USERNAME="$POSTGRESQL_USERNAME"
export DB_PASSWORD="$POSTGRESQL_PASSWORD"
export DB_SCHEME="$POSTGRESQL_SCHEME"
export DATABASE_URL="${DB_SCHEME}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:${DB_PORT}/${DB_PATH}"

# Strapi-specific environment variables
export JWT_SECRET="$PLATFORM_PROJECT_ENTROPY"
export API_TOKEN_SALT="$PLATFORM_PROJECT_ENTROPY"
```

And this is what is working to install it on Upsun:
```
export RELATIONSHIPS_JSON="$(echo $PLATFORM_RELATIONSHIPS | base64 --decode)"

# Set database environment variables
export DATABASE_HOSTNAME="$POSTGRESQL_HOSTNAME"
export DATABASE_HOST="$POSTGRESQL_HOST"                        --> missing one, required by Strapi
export DATABASE_PORT="$POSTGRESQL_PORT"
export DATABASE_PATH="$POSTGRESQL_PATH"
export DATABASE_USERNAME="$POSTGRESQL_USERNAME"
export DATABASE_PASSWORD="$POSTGRESQL_PASSWORD"
export DATABASE_SCHEME="$POSTGRESQL_SCHEME"
export DATABASE_URL="${DATABASE_SCHEME}://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_PATH}"

# Strapi-specific environment variables
export JWT_SECRET="$PLATFORM_PROJECT_ENTROPY"
export ADMIN_JWT_SECRET="$PLATFORM_PROJECT_ENTROPY"        --> missing one, required by Strapi
export API_TOKEN_SALT="$PLATFORM_PROJECT_ENTROPY"
export APP_KEYS="toBeModified1,toBeModified2"                                    --> missing one, required by Strapi
```

- envVar needs to start with `DATABASE_` as used in `database.js` 
- missing `DATABASE_HOST`
- missing `ADMIN_JWT_SECRET`
- missing `APP_KEYS`

You can have a look at the draft guide here:
https://docs.upsun.com.adds-strapi-guide-3o6f4xi-652soceglkw4u.eu-3.platformsh.site/get-started/strapi.html#customize-generated-environment-file

ps: and as for now, image NodeJs 18/20 is not generating the related service envVars in the container (`POSTGRESQL_*`) that's why in the guide i need to extract them one by one from `RELATIONSHIPS_JSON`

**Comment by gilzow** [comment]
The current version of `project:init` included with v5.0.0 of the upsun cli is missing the required `APP_KEYS` environment variable in the generated .environment file. 

Current contents of the `project:init` generated .environment file on a detected strapi application:

```
# Set database environment variables
export DB_HOST="$POSTGRESQL_HOST"
export DB_PORT="$POSTGRESQL_PORT"
export DB_PATH="$POSTGRESQL_PATH"
export DB_USERNAME="$POSTGRESQL_USERNAME"
export DB_PASSWORD="$POSTGRESQL_PASSWORD"
export DB_SCHEME="$POSTGRESQL_SCHEME"
export DATABASE_URL="${DB_SCHEME}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_PATH}"

# Set Strapi-specific environment variables
export DATABASE_HOST="$DB_HOST"
export DATABASE_PORT="$DB_PORT"
export DATABASE_NAME="$DB_PATH"
export DATABASE_USERNAME="$DB_USERNAME"
export DATABASE_PASSWORD="$DB_PASSWORD"
export DATABASE_SCHEME="$DB_SCHEME"

export ADMIN_JWT_SECRET="$PLATFORM_PROJECT_ENTROPY"
export JWT_SECRET="$PLATFORM_PROJECT_ENTROPY"
export API_TOKEN_SALT="$PLATFORM_PROJECT_ENTROPY"
```

**Comment by akalipetis** [comment]
@gilzow the issue with adding `APP_KEYS` is that this is probably better suited at a Platform.sh/Upsun secret or environment variable. It's not a value that should be statically set in the `.environment` file of the project.

I understand that the main reason for wanting the `APP_KEYS` in there, is that Strapi requires it by default - in that case, I would propose adding a fallback value in the code and a warning in case that fallback value is used.

An example snippet could be the following one:

```js
module.exports = ({ env }) => (
  if (!process.env.APP_KEYS) {
    console.warn("APP_KEYS is not set and will fallback to toBeModified1,toBeModified2");
    console.warn("Please set APP_KEYS as an environment variable"); 
  }
  {
  ...
  app: {
    keys: env.array("APP_KEYS", ["toBeModified1", "toBeModified2"]),
  },
});
```

How does this sound?

**Comment by flovntp** [comment]
this sounds good to me but, could you please add a link to the doc in the warning
```
    console.warn("Please set APP_KEYS as an environment variable"); 
    console.warn("For more information: https://docs.upsun.com/development/variables/set-variables.html#create-project-variables"); 
```
and yes, by default, Strapi needs this `API_KEYS` for session AFAIK : https://forum.strapi.io/t/error-middleware-strapi-session-app-keys-are-required/24948

**Comment by akalipetis** [comment]
@flovntp this should be added to the repository, not here - feel free to add the message that best describes the issue there.

I'll move on and close this one, as there's no change needed in Platformify.

**Comment by chadwcarlson** [comment]
@akalipetis Shouldn't we do the opposite? Set some default value for `APP_KEYS` using `PLATFORM_ENVIRONMENT` in `.environment`, but then document/prompt users to add the fallback in their code?
